### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Lapin0t** [flupe/compilo#2]
Hi, what's the licence for this project?

**Comment by flupe** [comment]
I guess it boils down to a simple choice between GNU GPLv3 and the MIT Licence. Not sure if enforcing the disclosure of modified code is relevant in our case. Should we care about how people use our project? Your call.

**Comment by Lapin0t** [comment]
If we are seeking for world domination of free software, the generally advised strategy is to use strong copyleft for anything whose adoption will not be harmed by strong copyleft, so that free software have an advantage (_ie_ for final programs or libraries providing original features). Weak copyleft is mainly useful if we are building a library for which weak copyleft or non-free alternatives already exist.

**Comment by flupe** [comment]
That's a very fair point. I've added the GPL license to the project. Now let's move on to the real deal.
